/**
 * Mock LLM for testing brief generation without hitting real APIs.
 *
 * Usage:
 *   const llm = new MockLLM();
 *   llm.setResponse(/aws\.bedrock/, JSON.stringify({ title: '...', highlights: [...] }));
 *   const response = await llm.complete('Generate brief for aws.bedrock...');
 */

export interface LLMResponse {
  content: string;
  usage: {
    prompt_tokens: number;
    completion_tokens: number;
  };
}

export interface MockLLMConfig {
  defaultLatencyMs?: number;
  failAfterCalls?: number;
}

export class MockLLM {
  private responses: Array<{ pattern: RegExp; response: string | (() => string) }> = [];
  private callCount = 0;
  private config: MockLLMConfig;

  constructor(config: MockLLMConfig = {}) {
    this.config = {
      defaultLatencyMs: 0,
      ...config,
    };
  }

  /**
   * Register a response for prompts matching the pattern.
   * Patterns are checked in order; first match wins.
   */
  setResponse(promptPattern: RegExp, response: string | (() => string)): void {
    this.responses.push({ pattern: promptPattern, response });
  }

  /**
   * Clear all registered responses.
   */
  clearResponses(): void {
    this.responses = [];
    this.callCount = 0;
  }

  /**
   * Get the number of times complete() was called.
   */
  getCallCount(): number {
    return this.callCount;
  }

  /**
   * Simulate an LLM completion call.
   */
  async complete(prompt: string): Promise<LLMResponse> {
    this.callCount++;

    // Simulate failure after N calls
    if (this.config.failAfterCalls && this.callCount > this.config.failAfterCalls) {
      throw new Error('MockLLM: Simulated API failure');
    }

    // Simulate latency
    if (this.config.defaultLatencyMs && this.config.defaultLatencyMs > 0) {
      await new Promise((resolve) => setTimeout(resolve, this.config.defaultLatencyMs));
    }

    // Find matching response
    for (const { pattern, response } of this.responses) {
      if (pattern.test(prompt)) {
        const content = typeof response === 'function' ? response() : response;
        return {
          content,
          usage: {
            prompt_tokens: Math.ceil(prompt.length / 4), // Rough estimate
            completion_tokens: Math.ceil(content.length / 4),
          },
        };
      }
    }

    throw new Error(
      `MockLLM: No response registered for prompt: "${prompt.slice(0, 100)}..."`,
    );
  }

  /**
   * Create a mock LLM that always returns a valid brief JSON.
   */
  static withDefaultBriefResponse(): MockLLM {
    const llm = new MockLLM();
    llm.setResponse(
      /.*/,
      JSON.stringify({
        title: 'Test Brief',
        highlights: [
          {
            topic: 'test.topic',
            what_happened: 'Test event happened [1]',
            why_it_matters: 'This matters for testing',
            suggested_action: 'Verify the test passes',
            citations: ['https://example.com/test'],
          },
        ],
        notes: 'Generated by MockLLM for testing',
      }),
    );
    return llm;
  }
}
